services:
  thumbnail_mapper:
    build:
      context: ./image-mapper
      dockerfile: Dockerfile
    container_name: thumbnail_mapper
    environment:
      - QUALITY=Thumbnail
      - VIDEOS=false
      - TIME=3600
    volumes:
        - /home/oskar/Bilder:/src:ro
        - thumbnail_images:/dst
  mobile_mapper:
    build:
      context: ./image-mapper
      dockerfile: Dockerfile
    container_name: mobile_mapper
    environment:
      - QUALITY=Mobile
      - VIDEOS=false
      - TIME=3600
    volumes:
        - /home/oskar/Bilder:/src:ro
        - mobile_images:/dst
  tv_mapper:
    build:
      context: ./image-mapper
      dockerfile: Dockerfile
    container_name: tv_mapper
    environment:
      - QUALITY=TV
      - VIDEOS=false
      - TIME=3600
    volumes:
        - /home/oskar/Bilder:/src:ro
        - tv_images:/dst
  mobile_image_server:
    build:
      context: ./http-image-server
      dockerfile: Dockerfile
    container_name: mobile_image_server
    volumes:
      - thumbnail_images:/thumbnail
      - mobile_images:/full
    ports:
      - 8080:80
  tv_image_server:
    build:
      context: ./http-image-server
      dockerfile: Dockerfile
    container_name: tv_image_server
    volumes:
      - thumbnail_images:/thumbnail
      - tv_images:/full
    ports:
      - 8081:80
volumes:
  thumbnail_images:
  mobile_images:
  tv_images:
