services:
  thumbnail_converter:
    build:
      context: ./image-mapper
      dockerfile: Dockerfile
    container_name: thumbnail_converter
    environment:
      - QUALITY=Thumbnail
      - VIDEOS=false
      - TIME=3600
    volumes:
        - /home/oskar/Bilder:/src
        - thumbnail_conv:/dst
  tv_http_image_server:
    build:
      context: ./http-image-server
      dockerfile: Dockerfile
    container_name: tv_http_image_server
    volumes:
      - thumbnail_conv:/thumbnail
      - thumbnail_conv:/full
    ports:
      - 8080:80
volumes:
  thumbnail_conv:
  mobile_conv:
  tv_conv:
