services:
  thumbnail_mapper:
    build:
      context: ./image-mapper
      dockerfile: Dockerfile
    container_name: thumbnail_mapper
    environment:
      - QUALITY=Thumbnail
      - VIDEOS=false
      - TIME=3600
    volumes:
        - /home/oskar/Bilder:/src:ro
        - thumbnail_images:/dst
    deploy:
      resources:
        limits:
          cpus: '0.25'
    init: true
  mobile_mapper:
    build:
      context: ./image-mapper
      dockerfile: Dockerfile
    container_name: mobile_mapper
    environment:
      - QUALITY=Mobile
      - VIDEOS=false
      - TIME=3600
    volumes:
        - /home/oskar/Bilder:/src:ro
        - mobile_images:/dst
    deploy:
      resources:
        limits:
          cpus: '0.25'
    init: true
  tv_mapper:
    build:
      context: ./image-mapper
      dockerfile: Dockerfile
    container_name: tv_mapper
    environment:
      - QUALITY=TV
      - VIDEOS=false
      - TIME=3600
    volumes:
        - /home/oskar/Bilder:/src:ro
        - tv_images:/dst
    init: true
    deploy:
      resources:
        limits:
          cpus: '0.25'
  mobile_image_server:
    build:
      context: ./http-image-server
      dockerfile: Dockerfile
    container_name: mobile_image_server
    volumes:
      - thumbnail_images:/thumbnail
      - mobile_images:/full
    ports:
      - 8080:80
    init: true
  tv_image_server:
    build:
      context: ./http-image-server
      dockerfile: Dockerfile
    container_name: tv_image_server
    volumes:
      - thumbnail_images:/thumbnail
      - tv_images:/full
    ports:
      - 8081:80
    init: true
volumes:
  thumbnail_images:
  mobile_images:
  tv_images:
